--- #YAML:1.0
name: AudioFile-Info-Ogg-Vorbis-Header-PurePerl
version: 1.03
author:
  - Dave Cross, E<lt>dave@dave.org.ukE<gt>
abstract: Perl extension to get
info from Ogg Vorbis files.
license: perl
requires:
  AudioFile::Info: 0
  Ogg::Vorbis::Header::PurePerl: 0
  perl: 5.6.0
build_requires:
  Module::Build: 0
dynamic_config: 1
provides:
  AudioFile::Info::Build:
    file: lib/AudioFile/Info/Build.pm
  AudioFile::Info::Ogg::Vorbis::Header::PurePerl:
    file: lib/AudioFile/Info/Ogg/Vorbis/Header/PurePerl.pm
    version: 1.03
generated_by: Module::Build version 0.2607
